#!/bin/sh

rm -rf $HOME/.cache/*
rm -rf $HOME/.local/state/nvim
rm -rf $HOME/.local/share/xorg/*.*
rm -rf $HOME/.local/share/xorg/*.old

# Define the Firefox profile path
PROFILE_DIR=~/.mozilla/firefox/

# Find the profile that ends with either '.default' or '.default-default'
PROFILE_NAME=$(ls $PROFILE_DIR | grep -E '\.default-default')
PROFILE_NAME_DEFAULT=$(ls $PROFILE_DIR | grep -E '\.default' | head -n 1)

# ls .mozilla/firefox/ | grep -E '\.default/'

# Check if a valid profile is found
if [ -z "$PROFILE_NAME" ]; then
  echo "No profile matching '.default' or '.default-default' found."
  exit 1
fi

if [ -z "$PROFILE_NAME_DEFAULT" ]; then
  echo "No profile matching '.default' found."
  exit 1
fi

# DEFAULT-DEFAULT
rm -rf $PROFILE_DIR/$PROFILE_NAME/bookmarkbackups/*
rm -rf $PROFILE_DIR/$PROFILE_NAME/bookmarkbackups/*.json
rm -rf $PROFILE_DIR/$PROFILE_NAME/bookmarkbackups/*.jsonlz4
rm -rf $PROFILE_DIR/$PROFILE_NAME/cookies.txt
rm -rf $PROFILE_DIR/$PROFILE_NAME/cookies.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME/cookies.sqlite-shm
rm -rf $PROFILE_DIR/$PROFILE_NAME/cookies.sqlite-wal
rm -rf $PROFILE_DIR/$PROFILE_NAME/storage/default/http*
rm -rf $PROFILE_DIR/$PROFILE_NAME/minidumps/*.dmp
rm -rf $PROFILE_DIR/$PROFILE_NAME/webappsstore.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME/formhistory.dat
rm -rf $PROFILE_DIR/$PROFILE_NAME/formhistory.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME/signons.txt
rm -rf $PROFILE_DIR/$PROFILE_NAME/signons2.txt
rm -rf $PROFILE_DIR/$PROFILE_NAME/signons3.txt
rm -rf $PROFILE_DIR/$PROFILE_NAME/signons.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME/logins.json
rm -rf $PROFILE_DIR/$PROFILE_NAME/sessionCheckpoints.json
rm -rf $PROFILE_DIR/$PROFILE_NAME/sessionstore*.js*
rm -rf $PROFILE_DIR/$PROFILE_NAME/sessionstore.bak*
rm -rf $PROFILE_DIR/$PROFILE_NAME/sessionstore-backups/previous.js*
rm -rf $PROFILE_DIR/$PROFILE_NAME/sessionstore-backups/recovery.js*
rm -rf $PROFILE_DIR/$PROFILE_NAME/sessionstore-backups/recovery.bak*
rm -rf $PROFILE_DIR/$PROFILE_NAME/sessionstore-backups/previous.bak
rm -rf $PROFILE_DIR/$PROFILE_NAME/sessionstore-backups/upgrade.js*-20*
rm -rf $PROFILE_DIR/$PROFILE_NAME/content-prefs.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME/SiteSecurityServiceState.txt
rm -rf $PROFILE_DIR/$PROFILE_NAME/history.dat
rm -rf $PROFILE_DIR/$PROFILE_NAME/downloads.rdf
rm -rf $PROFILE_DIR/$PROFILE_NAME/downloads.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME/places.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME/favicons.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME/AlternateServices.txt
rm -rf $PROFILE_DIR/$PROFILE_NAME/*.sqlite

# DEFAULT
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/bookmarkbackups/*
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/cookies.txt
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/cookies.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/cookies.sqlite-shm
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/cookies.sqlite-wal
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/storage/default/http*
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/minidumps/*.dmp
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/webappsstore.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/formhistory.dat
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/formhistory.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/signons.txt
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/signons2.txt
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/signons3.txt
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/signons.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/logins.json
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/sessionCheckpoints.json
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/sessionstore*.js*
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/sessionstore.bak*
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/sessionstore-backups/previous.js*
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/sessionstore-backups/recovery.js*
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/sessionstore-backups/recovery.bak*
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/sessionstore-backups/previous.bak
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/sessionstore-backups/upgrade.js*-20*
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/content-prefs.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/SiteSecurityServiceState.txt
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/history.dat
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/downloads.rdf
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/downloads.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/places.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/favicons.sqlite
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/AlternateServices.txt
rm -rf $PROFILE_DIR/$PROFILE_NAME_DEFAULT/*.sqlite
